server:
  port: 8081
management:
  security:
    enabled: false
message: '{cipher}7ccd5fcfd58a7645f3a51625297adb78a9a6d51e73603fc7265a7b53f8298b43'
helloservice:
  config:
    changeMe: Change Me new Message!
cloud:
  config:
    retry:
      maxAttempts: 10
      initial-interval: 5000
      max-interval: 10000
---
spring:
  profiles: hello1
server:
  port: 8083
---
spring:
  profiles: hello2
server:
  port: 8084
